[application]
name = "Λύπη"
default_platform = "android"
sub_package = "morph_app"

[bundle]
identifier = "com.morph.app"
publisher = "Morph Dev"
icon = [
	"assets/icons/macos/icon_32x32.png",
	"assets/icons/macos/icon_32x32@2x.png",
	"assets/icons/macos/icon_128x128.png",
	"assets/icons/macos/icon_128x128@2x.png",
	"assets/icons/macos/icon_256x256.png",
	"assets/icons/macos/icon_256x256@2x.png",
	"assets/icons/macos/icon_512x512.png",
	"assets/icons/macos/icon_512x512@2x.png",
]

[bundle.windows]
icon_path = "assets/icons/windows/app.ico"
