name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ] # Срабатывает при пуше в main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install Dioxus CLI
        run: cargo install dioxus-cli

      - name: Build Web App
        # Собираем проект под платформу web
        run: dx build --release --platform web

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # По умолчанию Dioxus собирает всё в папку dist
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4